### ISSUE TITLE
Plans for a LICENSE?

### ISSUE THREAD

**Issue by ckcr4lyf** [robertknight/ocrs#11]
Cool project! I was wondering about using this potentially as a library, but could not find any licensing information.

The closest thing was that the models are under an open license: https://github.com/robertknight/ocrs-models#datasets , but nothing about ocrs itself.

**Comment by robertknight** [comment]
Hello - The license is "MIT or Apache 2.0", as recommended by the [Rust API Guidelines project](https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive) and is specified in the `license` field of the [Cargo.toml](https://github.com/robertknight/ocrs/blob/8daf062cead28970dc8ad65ae1f695f6fb50cc6a/ocrs/Cargo.toml#L7) files. More generally you can find the license for any published Rust crate by looking at the "Metadata" section on the right-hand side of https://crates.io/crates/ocrs.
