### ISSUE TITLE
Building for WASM / WASI without SIMD

### ISSUE THREAD

**Issue by andreaTP** [robertknight/ocrs#113]
Hi :wave: and thanks for the great project!

I was trying to compile the CLI with wasi support and no simd but I couldn't get a usable artifact.

Seems like setting `RUSTFLAGS="-C target-feature=-simd128"` is not effective and there are still SIMD operations in the resulting wasm file.

I'm using a command line like:
```
RUSTFLAGS="-C target-feature=-simd128" cargo build --release --target wasm32-wasi --package ocrs-cli
```

I'm not familiar with this project, am I missing something?

**Comment by robertknight** [comment]
Thanks for the issue report. Some mistakes crept into the [rten](https://github.com/robertknight/rten) machine learning runtime where some WASM SIMD code paths were missing `#[cfg(target_feature = "simd128")]` conditionals. This has been fixed in https://github.com/robertknight/rten/pull/348.

I will note that non-SIMD builds are significantly slower (at least 2x), so using SIMD is recommended if possible.

**Comment by andreaTP** [comment]
Thanks a lot for the super quick answer!
Do I need to wait for releases or just update to the `main` branch?

> I will note that non-SIMD builds are significantly slower (at least 2x), so using SIMD is recommended if possible.

I would like to use this for a [Chicory](https://github.com/dylibso/chicory) demo, and 2X slower is already optimistic :sweat_smile: , I won't have time to implement the SIMD support in time :sweat_smile:

**Comment by robertknight** [comment]
> Do I need to wait for releases or just update to the main branch?

You can tell cargo to [override](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#working-with-an-unpublished-minor-version) the rten dependency to point at a specific commit, like so:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index f26dd67..ee388d6 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -9,3 +9,7 @@ members = [
 rten = { version = "0.13.1" }
 rten-imageproc = { version = "0.13.1" }
 rten-tensor = { version = "0.13.1" }
+
+[patch.crates-io]
+rten = { git = "https://github.com/robertknight/rten.git", rev = "ddba9ce6e70b1b4eb8add497a4bc2079e8e2d832" }
+rten-tensor = { git = "https://github.com/robertknight/rten.git", rev = "ddba9ce6e70b1b4eb8add497a4bc2079e8e2d832" }
```

> I would like to use this for a [Chicory](https://github.com/dylibso/chicory) demo, and 2X slower is already optimistic 😅 , I won't have time to implement the SIMD support in time 😅

For a demo, cheat by using an image without too much text :)
