### ISSUE TITLE
Add document for supported Characters/Languages in README

### ISSUE THREAD

**Issue by xring** [robertknight/ocrs#16]
As mentioned in https://github.com/robertknight/ocrs/issues/8, seems like only Latin characters are supported currently.

It will be great to add document to track supported / WIP / TODO Characters/Languages, it can also help community to work on related task together.

**Comment by robertknight** [comment]
Done! - Regarding collaboration around more languages, I first need to add the basic infrastructure (eg. better model training documentation), and then it will be possible for people with expertise in various languages to contribute.
