### ISSUE TITLE
Could this be used to extract tabular data from photos of supplements?

### ISSUE THREAD

**Issue by lilouartz** [robertknight/ocrs#47]
![0108_nowproductlabels](https://github.com/robertknight/ocrs/assets/167234340/6d25c5c1-d91b-4a35-967a-d1823ac3d7eb)

My dataset are photos such as this one.

I am looking for a software that could extract tabular information from these photos.

Is this a good use case for ocrs?

**Comment by robertknight** [comment]
Ocrs can read the words and provide their location in the image, but it can't determine whether a word is part of a table and which cell/row it belongs to, so you would need to write code to do that. There is a general issue about table support at https://github.com/robertknight/ocrs/issues/39.
